#!/bin/bash
#set -x
function set_context_f(){
source $DEV0_HELPERS/is_in_array_f
# $1: suite-name context is set to suite level
# 
# $1: activity-name 
# 
# $1: suite-name
# $2: activity-name
# 
# $1: suite-name
# $2: activity-name
# $3: sub-suite-name
# set -x # uncomment to debug

if [[ "$DEV0" == "" ]];then
  echo "Environment variables for DEV0 are not defined."
  echo "Please ensure that dev0rc has been sourced in your"
  echo "~/.bashrc, or source dev0rc from the command line"
  return 1
fi

sed_1="sed -e s|${DEV0_TREES}/|| -e s/local// -e s/ARCHIVE// -e s/.vscode//"

suites_a=($(find $DEV0_TREES -maxdepth 1 -mindepth 1 -type d| $sed_1 -))
suite_activities_a=($(find $DEV0_TREES -maxdepth 2 -mindepth 2 -type d|$sed_1))
repositories_a=($(find $DEV0_TREES -maxdepth 3 -mindepth 3 -type d|$sed_1))

context_file=$DEV0_USER_DATA/context
if [[ "$1$2$3" == "" ]];then
  if [[ -e $context_file ]];then
    current_context=$(cat $context_file)
    context_path=$current_context
    if [[ -e ${context_path}/local/$(basename $context_path).code-workspace ]]; then
      code_workspace_file=$context_path/local/$(basename $context_path).code-workspace
    elif [[ -e $context_path/$(basename $context_path).code-workspace ]]; then
      code_workspace_file=$context_path/$(basename $context_path).code-workspace
    fi
  else
    echo "No context data found in $context_file"
    echo "provide suite, suite and workspace or suite, workspace and sub-suite"
    exit 1
  fi
else
  suite="$1"
  context_path=$DEV0_TREES/$suite
  code_workspace_file="$suite.code-workspace"
 
  if  ! is_in_array_f "$suite"  "${suites_a[@]}";then
      echo "Application Suite $suite not found in $DEV0_TREES"
      return 1
  fi
  if [[ ! "$2" == "" ]];then
    activity="$2"
    context_path=$context_path/$activity
    code_workspace_file="${context_path}/${activity}.code-workspace"
    if ! is_in_array_f "$suite/$activity"  "${suite_activities_a[@]}";then
      echo "Activity $suite/$Activity not found"
      return 1
    fi
  fi

  if [[ ! "$3" == "" ]];then
    repository="$3"
    context_path=$context_path/$repository
    code_workspace_file="$repository.code-workspace"

    if [[ ! -e $context_path ]]; then
      echo "Repository $repository not found"
      echo "$context_path does not exist"
      return 1
    fi
  fi
fi
echo $context_path >$context_file
}
