#!/bin/bash
echo getRepositories
if [ ! "$suiteName" ] || [ "$1" ];then
  # shellcheck source=getSuite
  source "$DEV_UTILS_PATH"/suite/getSuite "$1"
fi
startingPwd=$PWD
declare -g suiteName
declare -ga Repositories
Repositories=()
oldRepositoriesDir="$DEV_SUITES_PATH"/"$suiteName"/repositories
if [[ -e "$oldRepositoriesDir" ]]; then
  cd "$oldRepositoriesDir" || return 1
  shopt -s nullglob dotglob
  files=(*.git)
  for repo in "${files[@]}"; do
    #echo "found $repo"
    Repositories+=( "${repo%%\.git}" )
  done
   # shellcheck source-path=path/to/directory
  cd "$startingPwd" || return 1
fi