#!/bin/bash
#  SPDX-FileName: getCMakeBuildType
#  SPDX-FileComment:User by run and build commands
#  SPDX-FileCopyrightText: Copyright (C) 2024 Patrick Callahan
#  SPDX-License-Identifier: GPL-2.0-or-later

# source $DEV_APP_DIR/CMakeBuildType
# source $DEV_APP_DIR/CMakeBuildType "invalid"
# if called does nothing but set the "previous" CmakeBuildType
declare -g suite
declare -g cMakeBuildType=""

declare -A _CMakeBuildTypes_lookup=(
    ["debug"]="Debug"                   ["d"]="Debug"
    ["release"]="Release"               ["r"]="Release"
    ["relwithdebinfo"]="RelWithDebInfo" ["rd"]="RelWithDebInfo"
    ["minsizerel"]="MinSizeRel"         ["m"]="MinSizeRel"      )

for arg in "$@"; do
  if [[ "$arg" != "" && ${_CMakeBuildTypes_lookup["${1,,}"]+abc} ]]; then
    cMakeBuildType=${_CMakeBuildTypes_lookup["${1,,}"]}
    break
    if [[ "$arg" == "--" ]];then break; fi
  fi
done
if [[ $suite != "" ]]; then
  echo "$cMakeBuildType" >"$DEV_SUITES_DIR"/"$suite"/project/cMakeBuildType
fi
set +x