#!/bin/bash
#  SPDX-FileName: getSuite
#  SPDX-FileComment:User by run and build commands
#  SPDX-FileCopyrightText: Copyright (C) 2024 Patrick Callahan
#  SPDX-License-Identifier: GPL-2.0-or-later


if [[ "$1" == "" ]]; then
  suite="$(<"$DEV_SUITES_DIR"/currentSuite)";
  if [[ "$suite" == "" ]]; then  echo "Could not find a value for most recent Suite Name"; $exit 1; fi
elif [[ -e $DEV_SUITES_DIR/"$1" ]]; then
  suite=$1
fi

