#!/bin/bash
echo getWorktrees
if [ ! "$suiteName" ] || [ "$1" ];then
  # shellcheck source=getSuite
  source "$DEV_APP_DIR"/utils/getSuite "$1"
fi
startingPwd=$PWD
declare -g suiteName
declare -ga Worktrees
Worktrees=()
oldWorktreesDir="$DEV_SUITES_DIR"/"$suiteName"/worktrees
if [[ -e "$oldWorktreesDir" ]]; then
  cd "$oldWorktreesDir" || return 1
  shopt -s nullglob dotglob
  files=(*)
  for worktree in "${files[@]}"; do
    #echo "found $repo"
    if [[ -e $worktree/.git ]]; then
      Worktrees+=( "${worktree}" )
    fi
  done
   # shellcheck source-path=path/to/directory
  cd "$startingPwd" || return 1
fi