#!/bin/bash
#  SPDX-FileName: dev0/app/build
#  SPDX-FileComment:User by run and build commands
#  SPDX-FileCopyrightText: Copyright (C) 2024 Patrick Callahan
#  SPDX-License-Identifier: GPL-2.0-or-later
declare exit
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  exit="exit"
else
  exit="return"
fi
if [[ "$1" == "-x" ]]; then { set -x; shift; } fi
declare -g suite
# shellcheck disable=SC1091
source "$DEV_UTILS_PATH"/suite/getSuite "$@"
declare -g suite
source "$DEV_UTILS_PATH"/suite/getSuite "$@"
declare -g gitReference
source "$DEV_UTILS_PATH"/getGitReference "$2"

projectPath="$DEV_SUITES_PATH"/"$suite"/project

if [[ ! -e "$projectPath" ]]; then
  echo Could not find "$projectPath directory" ;  $exit 1
fi
projectBuildScript=$projectPath/build
if [[ ! -e "$projectBuildScript" ]]; then
  echo Could not find "$projectBuildScript script" ; $exit 1;
fi

source $projectBuildScript "$@"
