#!/bin/bash
#  SPDX-FileName: dev0/app/run
#  SPDX-FileComment:User by run and build commands
#  SPDX-FileCopyrightText: Copyright (C) 2024 Patrick Callahan
#  SPDX-License-Identifier: GPL-2.0-or-later
declare  exit
declare -g exit
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  exit="exit"
else
  exit="return"
fi
declare -g suite
source "$DEV_COMMANDS_PATH"/suite/getSuite "$1"
projectPath="$DEV_SUITES_PATH"/"$suite"/project
if [[ ! -d "$projectPath" ]]; then
  echo Could not find "$projectPath directory" ; $exit 1
fi
projectRunScript=$projectPath/run
if [[ ! -f "$projectRunScript" ]]; then
  echo Could not find "$projectRunScript script" ; $exit 1
fi

export gitReference
export suite
echo "$projectRunScript" "$@"
# shellcheck disable=SC2086
# shellcheck disable=SC1090
$projectRunScript "$@"


