#!/bin/bash
#  SPDX-FileName: setExit
#  SPDX-FileComment:User by run and build commands
#  SPDX-FileCopyrightText: Copyright (C) 2024 Patrick Callahan
#  SPDX-License-Identifier: GPL-2.0-or-later
#declare -g exit
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  exit="exit"
else
  exit="return"
fi