#!/bin/bash

# set -x #uncomment for debugging

source $DEV0_HELPERS/set_context_f

set_context_f $1 $2 $3
if [[ $? == 0 ]]; then
sed_1="sed -e s|${DEV0_TREES}/||"
IFS='/' read -r -a context <<< $(echo $context_path|$sed_1)
current_suite=${context[0]}
current_activity=${context[1]}
current_repository=${context[2]}

  if [ -z "$BASH_SOURCE" ]; then
    echo $context_path
  else
    cd $context_path
  fi
fi