#!/bin/bash
echo getWorktrees
if [ ! "$suiteName" ] || [ "$1" ];then
  # shellcheck source=getSuite
  source "$DEV_UTILS_PATH"/suite/getSuite "$1"
fi
startingPwd=$PWD
declare -g suiteName
declare -ga Worktrees
Worktrees=()
if [[ -e "$DEV_SUITES_PATH"/"$suiteName"/worktrees ]]; then
  worktreesDir="$DEV_SUITES_PATH"/"$suiteName"/worktrees
else
  worktreesDir="$DEV_SUITES_PATH"/worktrees
fi
if [[ -e "$worktreesDir" ]]; then
  cd "$worktreesDir" || return 1
  shopt -s nullglob dotglob
  files=(*)
  for worktree in "${files[@]}"; do
    #echo "found $repo"
    if [[ -e $worktree/.git ]]; then
      Worktrees+=( "${worktree}" )
    fi
  done
   # shellcheck source-path=path/to/directory
  cd "$startingPwd" || return 1
fi